name: Build and test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  macos_test:
    name: Test macOS
    strategy:
      matrix:
        include:
          - { os: "macos-11.0", xcode: "Xcode_13.2.1" }
          - { os: "macos-12.0", xcode: "Xcode_13.4.1" }

    runs-on: ${{ matrix.macVersion }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run the test suite on ${{ matrix.os }}
        shell: bash
        run: |
          set -ex
          sudo xcode-select --switch /Applications/${{ matrix.xcode }}.app/Contents/Developer/
          swift --version
          swift test

  ubuntu_test:
    name: Test Ubuntu
    strategy:
      matrix:
        ubuntuVersion: ["ubuntu-18.04", "ubuntu-20.04"]

    runs-on: ${{ matrix.ubuntuVersion }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run the test suite on ${{ matrix.ubuntuVersion }}
        shell: bash
        run: |
          set -ex
          swift --version
          swift test --enable-test-discovery
